import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    width: width,
    height: height,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.1)', 
    paddingVertical: 20,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    width: width * 0.9,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 20,
  },
  headerText: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#34495e',
    textAlign: 'center',
    flex: 1,
  },
  menuButton: {
    position: 'absolute',
    left: 0,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 5,
    zIndex: 10,
  },
  menuDropdown: {
    position: 'absolute',
    top: 60,
    left: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 10,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    zIndex: 10,
  },
  menuItem: {
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  menuText: {
    fontSize: 16,
    color: '#2c3e50',
  },
  tableContainer: {
    width: '100%',
    marginBottom: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 10,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#2980b9',
  },
  table: {
    width: '100%',
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ecf0f1',
  },
  tableCell: {
    fontSize: 16,
    color: '#2c3e50',
  },
  tableHeader: {
    fontWeight: 'bold',
    color: '#8e44ad',
  },
  descuentoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  descuentoLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 10,
    color: '#2c3e50',
  },
  descuentoInput: {
    flex: 1,
    padding: 10,
    backgroundColor: '#ecf0f1',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#bdc3c7',
    fontSize: 16,
    color: '#2c3e50',
  },
  button: {
    backgroundColor: '#800000',
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
    width: width * 0.6,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.9,
    shadowRadius: 30,
    elevation: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
  },
});
